---
# tasks file for python-lxml
- name: install libxml and dependencies for the xml module
  yum: name="{{item}}" state=present
  with_items:
    - gcc
    - make
    - libxslt
    - libxslt-devel
    - libxml2
    - libxml2-devel
  when: ansible_distribution in ('CentOS','RedHat','Amazon')
  environment: proxy_env

- name: install lxml
  pip: name=lxml state=present
  environment: proxy_env
